// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChatConnect(arg1:string,arg2:string,arg3:number):Promise<string>;

export function ChatLeave():Promise<void>;

export function ChatSend(arg1:string):Promise<void>;

export function ChatStatus():Promise<main.ChatStatus>;

export function GenerateCode():Promise<string>;

export function GetServerStatus():Promise<main.ServerStatus>;

export function StartServer(arg1:string,arg2:number,arg3:string,arg4:number):Promise<string>;

export function StopServer():Promise<void>;
