// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChatConnect(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChatConnect'](arg1, arg2, arg3);
}

export function ChatLeave() {
  return window['go']['main']['App']['ChatLeave']();
}

export function ChatSend(arg1) {
  return window['go']['main']['App']['ChatSend'](arg1);
}

export function ChatStatus() {
  return window['go']['main']['App']['ChatStatus']();
}

export function GenerateCode() {
  return window['go']['main']['App']['GenerateCode']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function StartServer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartServer'](arg1, arg2, arg3, arg4);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
